-- Art TTM LINE bot memory schema
create table if not exists public.line_members (
  scope_id text not null,
  user_id text not null,
  display_name text,
  picture_url text,
  last_seen_at timestamptz not null default now(),
  primary key (scope_id, user_id)
);

create table if not exists public.line_messages (
  id bigint generated by default as identity primary key,
  scope_id text not null,
  user_id text,
  display_name text,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists line_messages_scope_created_idx
  on public.line_messages (scope_id, created_at desc);

create table if not exists public.line_memories (
  id bigint generated by default as identity primary key,
  scope_id text not null,
  user_id text,
  display_name text,
  memory_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists line_memories_scope_created_idx
  on public.line_memories (scope_id, created_at desc);

alter table public.line_members enable row level security;
alter table public.line_messages enable row level security;
alter table public.line_memories enable row level security;

-- The Render server uses the Supabase service-role/secret key.
-- Do not expose that key to LINE clients or commit it to GitHub.
